energy_usage <- read.table("household_power_consumption.txt",sep=";",header = TRUE)
energy_usage <- subset(energy_usage,Date=="1/2/2007" | Date=="2/2/2007")
energy_usage <- transform(energy_usage,Global_active_power=as.numeric(as.character(energy_usage$Global_active_powe)))
png(file ="plot1.png",bg="transparent")
hist(energy_usage$Global_active_power,xlab = "Global Active Power (kilowatts)",col="red",main ="Global Active Power",bg="transparent")
dev.off()